/**
 * init-wl.ts — Set Merkle WL root and start mint on deployed DopamilioNFT
 *
 * Usage (from contracts/ folder):
 *   OPNET_MNEMONIC="..." npx tsx init-wl.ts <contractAddress>
 *
 * Reads wl-root.txt (generated by generate-merkle.ts) and:
 *   1. Calls setWLRoot(root) to set the Merkle root on-chain
 *   2. Calls startMint() to activate the WL phase
 *
 * SECURITY: mnemonic only via env var — NEVER hardcoded.
 */
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { networks } from '@btc-vision/bitcoin';
import {
    ABIDataTypes,
    Mnemonic,
    MLDSASecurityLevel,
    AddressTypes,
    Address,
} from '@btc-vision/transaction';
import { BitcoinAbiTypes, BitcoinInterfaceAbi, getContract, JSONRpcProvider } from 'opnet';

const RPC_URL = 'https://testnet.opnet.org';
const NETWORK     = networks.opnetTestnet;

const args = process.argv.slice(2);
if (args.length < 1) {
    console.error('Usage: OPNET_MNEMONIC="..." npx tsx init-wl.ts <contractAddress>');
    process.exit(1);
}
const CONTRACT_ADDR = args[0];

const mnemonic = process.env.OPNET_MNEMONIC;
if (!mnemonic) {
    console.error('ERROR: set OPNET_MNEMONIC env var');
    process.exit(1);
}

// Read root from wl-root.txt
const rootFile = resolve(__dirname, 'wl-root.txt');
let rootHex: string;
try {
    rootHex = readFileSync(rootFile, 'utf8').trim();
} catch {
    console.error('ERROR: wl-root.txt not found — run generate-merkle.ts first');
    process.exit(1);
}
if (!/^[0-9a-f]{64}$/i.test(rootHex)) {
    console.error('ERROR: wl-root.txt must contain a 64-char hex string');
    process.exit(1);
}

const rootBigInt = BigInt('0x' + rootHex);

const mnemonicObj = new Mnemonic(mnemonic!, '', NETWORK, MLDSASecurityLevel.LEVEL1);
const wallet      = mnemonicObj.deriveOPWallet(AddressTypes.P2WPKH, 0);

function bytesToHex(b: Uint8Array): string {
    return Array.from(b).map(x => x.toString(16).padStart(2, '0')).join('');
}

const senderAddr = Address.fromString(
    wallet.address.toString(),
    bytesToHex(wallet.keypair.publicKey as Uint8Array),
);

console.log('Deployer P2TR   :', wallet.p2tr);
console.log('Deployer OPNet  :', wallet.address.toString());
console.log('Contract        :', CONTRACT_ADDR);
console.log('WL Root (hex)   :', rootHex);

const provider = new JSONRpcProvider({ url: RPC_URL, network: NETWORK });

async function sleep(ms: number): Promise<void> {
    return new Promise(r => setTimeout(r, ms));
}

async function sendTx(sim: any, label: string): Promise<void> {
    if (sim.revert) throw new Error(`${label} reverted: ${sim.revert}`);
    const receipt = await sim.sendTransaction({
        signer: wallet.keypair,
        mldsaSigner: wallet.mldsaKeypair,
        refundTo: wallet.p2tr,
        network: NETWORK,
        maximumAllowedSatToSpend: 100_000n,
    });
    if (!receipt) throw new Error(`${label}: no receipt`);
    console.log(`  OK ${label} TX: ${receipt.transactionId ?? ''}`);
    await sleep(12_000); // wait for indexer to process
}

const ABI: BitcoinInterfaceAbi = [
    {
        name: 'setWLRoot',
        inputs:  [{ name: 'root', type: ABIDataTypes.UINT256 }],
        outputs: [{ name: 'success', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'startMint',
        inputs:  [],
        outputs: [{ name: 'success', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'getPhase',
        inputs:  [],
        outputs: [{ name: 'phase', type: ABIDataTypes.UINT8 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'getWLRoot',
        inputs:  [],
        outputs: [{ name: 'root', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
];

async function main(): Promise<void> {
    const contract = getContract(CONTRACT_ADDR, ABI, provider, NETWORK, senderAddr);

    // Verify current phase (should be 0 = INACTIVE)
    const phaseSim = await (contract as any).getPhase();
    const phase = Number(phaseSim.properties?.phase ?? phaseSim);
    console.log('\nCurrent phase:', phase, '(expected 0 = INACTIVE)');
    if (phase !== 0) {
        console.warn('WARNING: Phase is not 0. Continuing anyway...');
    }

    // Step 1: setWLRoot
    console.log('\n--- Step 1: setWLRoot ---');
    const setRootSim = await (contract as any).setWLRoot(rootBigInt);
    await sendTx(setRootSim, 'setWLRoot');

    // Verify root was set (best-effort — indexer may lag)
    const rootSim = await (contract as any).getWLRoot();
    const storedRoot = (rootSim.properties?.root ?? rootSim).toString(16).padStart(64, '0');
    console.log('Stored root (hex):', storedRoot);
    if (storedRoot !== rootHex.toLowerCase()) {
        console.warn('WARNING: Root not visible yet (indexer lag) — continuing to startMint');
    } else {
        console.log('Root verified OK');
    }

    // Step 2: startMint
    console.log('\n--- Step 2: startMint ---');
    const startSim = await (contract as any).startMint();
    await sendTx(startSim, 'startMint');

    // Verify phase is now WL (phase 2)
    const phaseAfterSim = await (contract as any).getPhase();
    const phaseAfter = Number(phaseAfterSim.properties?.phase ?? phaseAfterSim);
    console.log('Phase after startMint:', phaseAfter, '(expected 2 = WL)');

    console.log('\n=================================================================');
    console.log(' WL initialization complete!');
    console.log(' Contract      :', CONTRACT_ADDR);
    console.log(' WL Root       :', rootHex);
    console.log(' Phase         :', phaseAfter, '(2 = WL, WL lasts 1.5 hours)');
    console.log(' Next: update CONTRACT_ADDR in index.html, then git push');
    console.log('=================================================================');
}

main().catch((err) => {
    console.error('init-wl failed:', err);
    process.exit(1);
});
